import Head from 'next/head'
import Image from 'next/image'
import styles from '@src/styles/Home.module.css'

 

export default function Home() {
  return (
    <>
      <Head>
        <title>Food Delivery App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Food Delivery App</h1>
    </>
  )
}
